export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS migrations (
    version INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    applied_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    genre TEXT,
    platform TEXT,
    target_words INTEGER,
    current_words INTEGER NOT NULL DEFAULT 0,
    style TEXT,
    status TEXT NOT NULL DEFAULT 'planning',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS world_items (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    name TEXT NOT NULL,
    content TEXT NOT NULL,
    importance INTEGER NOT NULL DEFAULT 3,
    tags TEXT NOT NULL DEFAULT '[]',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_world_items_project_type ON world_items(project_id, type)`,
  `CREATE TABLE IF NOT EXISTS characters (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    aliases TEXT NOT NULL DEFAULT '[]',
    role TEXT,
    personality TEXT,
    motivation TEXT,
    ability TEXT,
    appearance TEXT,
    relationship_summary TEXT,
    current_state TEXT,
    power_level TEXT,
    location TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    first_appearance_chapter INTEGER,
    last_appearance_chapter INTEGER,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_characters_project_name ON characters(project_id, name)`,
  `CREATE TABLE IF NOT EXISTS character_relationships (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    character_a_id TEXT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    character_b_id TEXT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    relationship_type TEXT NOT NULL,
    description TEXT,
    current_state TEXT,
    tension_level INTEGER,
    updated_chapter_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS volumes (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    volume_index INTEGER NOT NULL,
    title TEXT NOT NULL,
    goal TEXT,
    conflict TEXT,
    start_chapter INTEGER,
    end_chapter INTEGER,
    summary TEXT,
    status TEXT NOT NULL DEFAULT 'planned',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(project_id, volume_index)
  )`,
  `CREATE TABLE IF NOT EXISTS chapter_outlines (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    volume_id TEXT REFERENCES volumes(id) ON DELETE SET NULL,
    chapter_index INTEGER NOT NULL,
    title TEXT NOT NULL,
    goal TEXT,
    conflict TEXT,
    key_events TEXT,
    required_characters TEXT NOT NULL DEFAULT '[]',
    required_foreshadowing TEXT NOT NULL DEFAULT '[]',
    ending_hook TEXT,
    status TEXT NOT NULL DEFAULT 'planned',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(project_id, chapter_index)
  )`,
  `CREATE TABLE IF NOT EXISTS chapters (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    volume_id TEXT REFERENCES volumes(id) ON DELETE SET NULL,
    chapter_index INTEGER NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    summary TEXT,
    word_count INTEGER NOT NULL DEFAULT 0,
    opening TEXT,
    ending TEXT,
    hook TEXT,
    involved_characters TEXT NOT NULL DEFAULT '[]',
    involved_world_items TEXT NOT NULL DEFAULT '[]',
    status TEXT NOT NULL DEFAULT 'draft',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(project_id, chapter_index)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_chapters_project_chapter ON chapters(project_id, chapter_index DESC)`,
  `CREATE TABLE IF NOT EXISTS foreshadowings (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    introduced_chapter_id TEXT REFERENCES chapters(id) ON DELETE SET NULL,
    expected_resolve_chapter INTEGER,
    resolved_chapter_id TEXT REFERENCES chapters(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'open',
    importance INTEGER NOT NULL DEFAULT 3,
    related_characters TEXT NOT NULL DEFAULT '[]',
    related_world_items TEXT NOT NULL DEFAULT '[]',
    notes TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_foreshadowings_project_status ON foreshadowings(project_id, status)`,
  `CREATE TABLE IF NOT EXISTS timeline_events (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    chapter_id TEXT REFERENCES chapters(id) ON DELETE SET NULL,
    event_order INTEGER NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    involved_characters TEXT NOT NULL DEFAULT '[]',
    location TEXT,
    impact TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_timeline_project_order ON timeline_events(project_id, event_order, created_at)`,
  `CREATE TABLE IF NOT EXISTS canon_facts (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    source_type TEXT NOT NULL,
    source_id TEXT,
    fact_type TEXT NOT NULL,
    content TEXT NOT NULL,
    confidence REAL NOT NULL DEFAULT 0.8,
    importance INTEGER NOT NULL DEFAULT 3,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_canon_facts_project_type ON canon_facts(project_id, fact_type)`,
  `CREATE TABLE IF NOT EXISTS writing_rules (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    rule_type TEXT NOT NULL,
    content TEXT NOT NULL,
    priority INTEGER NOT NULL DEFAULT 100,
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_writing_rules_project_priority ON writing_rules(project_id, priority)`,
  `CREATE TABLE IF NOT EXISTS project_snapshots (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    label TEXT,
    notes TEXT,
    content TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_project_snapshots_project_created ON project_snapshots(project_id, created_at DESC)`,
  `CREATE VIRTUAL TABLE IF NOT EXISTS chapters_fts USING fts5(
    project_id UNINDEXED,
    chapter_id UNINDEXED,
    title,
    summary,
    content
  )`,
  `CREATE VIRTUAL TABLE IF NOT EXISTS world_items_fts USING fts5(
    project_id UNINDEXED,
    world_item_id UNINDEXED,
    name,
    content,
    tags
  )`,
] as const;
